# Generated by Django 5.0.2 on 2024-02-09 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsection', '0001_initial'),
        ('tour', '0002_tourdetails_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='traindetails',
            name='Tour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tour.toursoffered'),
        ),
    ]
