# Generated by Django 5.0.2 on 2024-02-09 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsection', '0002_traindetails_tour'),
        ('tour', '0002_tourdetails_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traindetails',
            name='Tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.toursoffered'),
        ),
    ]
