# Generated by Django 5.0.2 on 2024-02-16 11:51

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsection', '0003_alter_traindetails_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='Aadhaar_No',
            field=models.BigIntegerField(validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhaar number must be exactly  12 digits', 'Invalid number')]),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='Phone_No',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN'),
        ),
    ]
