# Generated by Django 5.0.2 on 2024-02-09 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToursOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tour_Name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 'SLT_TOURS_OFFERED',
            },
        ),
        migrations.CreateModel(
            name='TourDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_Cost', models.IntegerField()),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('No_Of_Days', models.IntegerField()),
                ('Tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.toursoffered')),
            ],
            options={
                'db_table': 'SLT_TOUR_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='DayWiseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.IntegerField()),
                ('Schedule', models.TextField()),
                ('Tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.toursoffered')),
            ],
            options={
                'db_table': 'SLT_DAY_WISE_SCHEDULE',
            },
        ),
        migrations.CreateModel(
            name='VisitingPlacesInTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(max_length=255)),
                ('Tour', models.ManyToManyField(to='tour.toursoffered')),
            ],
            options={
                'db_table': 'SLT_VISTING_PLACE_IN_TOUR',
            },
        ),
    ]
