# Generated by Django 5.0.2 on 2024-02-16 11:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_tourdetails_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitingplacesintour',
            name='Tour',
        ),
        migrations.AddField(
            model_name='visitingplacesintour',
            name='Tour',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='tour.toursoffered'),
            preserve_default=False,
        ),
    ]
